@baseUrl = https://xc8jbrf4-3000.euw.devtunnels.ms/api/

# @name login
POST {{baseUrl}}users/login
Content-Type: application/json

{ 
  "email": "outlook_5CC4867C4B04E2E3@outlook.com", 
  "password": "examplepwd12345"
}

# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjNhNWE1MmUyY2E1NzFiZmViM2ExNyIsImlhdCI6MTcyMzYzMzg5MSwiZXhwIjoxNzIzNjM3NDkxfQ.IQuq3oVusYimY516OGB8UTmxedlnrojVAgntHe8iufE",
#   "user": {
#     "email": "a.cross1@gmail.com",
#     "subscription": "starter"
#   }
# }
###

@authToken = Authorization: Bearer {{login.response.body.$.token}}

get {{baseUrl}}contacts
{{authToken}}
###
get {{baseUrl}}contacts/66b5f8d080b4092880d59c06
{{authToken}}
###

POST {{baseUrl}}contacts
{{authToken}}
Content-Type: application/json

{
  "name": "Allen Raymond",
  "email": "nulla.ante@vestibul.co.uk",
  "phone": "(992) 914-3792"
}

###
PATCH {{baseUrl}}contacts/66b5f8d080b4092880d59c06
{{authToken}}
Content-Type: application/json

{
 "name": "Allen Raymond1"
}
###
PATCH {{baseUrl}}contacts/66b5f9c680b4092880d59c0f/favorite
{{authToken}}
Content-Type: application/json

{
 "favorite": true
}
###

DELETE {{baseUrl}}contacts/66b5f8d080b4092880d59c06
{{authToken}}
###
POST {{baseUrl}}users/signup
Content-Type: application/json

{ 
  "email": "outlook_5CC4867C4B04E2E3@outlook.com", 
  "password": "examplepwd12345"
}

# {
#   "email": "a.cross1@gmail.com",
#   "subscription": "starter"
# }
###
GET {{baseUrl}}users/current
{{authToken}}

# {
#   "email": "a.cross1@gmail.com",
#   "subscription": "starter"
# }
###
GET {{baseUrl}}users/logout
{{authToken}}

###
