@baseUrl = https://xc8jbrf4-3000.euw.devtunnels.ms/api/

# @name login
POST {{baseUrl}}users/login
Content-Type: application/json

{ 
  "email": "outlook_5CC4867C4B04E2E3@outlook.com", 
  "password": "examplepwd12345"
}

# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjNhNWE1MmUyY2E1NzFiZmViM2ExNyIsImlhdCI6MTcyMzYzMzg5MSwiZXhwIjoxNzIzNjM3NDkxfQ.IQuq3oVusYimY516OGB8UTmxedlnrojVAgntHe8iufE",
#   "user": {
#     "email": "a.cross1@gmail.com",
#     "subscription": "starter"
#   }
# }
###

@authToken = Authorization: Bearer {{login.response.body.$.token}}

###
POST {{baseUrl}}users/signup
Content-Type: application/json

{ 
  "name": "Me",
  "email": "outlook_5CC4867C4B04E2E3@outlook.com", 
  "password": "examplepwd12345"
}

# {
#   "email": "a.cross1@gmail.com",
#   "subscription": "starter"
# }
###
GET {{baseUrl}}users/current
{{authToken}}

# {
#   "email": "a.cross1@gmail.com",
#   "subscription": "starter"
# }
###
GET {{baseUrl}}users/logout
{{authToken}}

###
POST {{baseUrl}}calc
{{authToken}}
Content-Type: application/json

{
  "age": 25,
    "height": 180,
    "weight": 65,
    "bloodType": 1,
    "desiredWeight": 64.5
}
###
GET {{baseUrl}}calc
{{authToken}}
###
GET {{baseUrl}}products/?search=pea&page=3
###
POST {{baseUrl}}diary/2024-09-15
{{authToken}}
Content-Type: application/json

{
  "product": "5d51694802b2373622ff554c",
  "weight": 50
}
###
  # "calories": -350
DELETE {{baseUrl}}diary/2024-09-15
{{authToken}}
Content-Type: application/json

["66e758308e5555b50da40093","66e7653b2a2ce6ab0081410e"]
###
GET {{baseUrl}}diary/2024-09-15
{{authToken}}
###